version: '3'

services:

  mongo_db:
    image: mongo:latest
    ports:
      - "27017:27017"

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    environment:
      REACT_APP_BACKEND_BASE_URL: http://backend:8080
      REACT_APP_NODE_ENV: dev
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - backend

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    environment:
      SHIPA_GEN_BACKEND_PORT: 8080
      SHIPA_GEN_MONGO_URI: mongodb://mongo_db:27017
      SHIPA_SERVER_BASE_URL: https://target.shipa.cloud:443
      SHIPA_GEN_AUTH_STORAGE: mongo
      SHIPA_GEN_AUTH_MONGO_DB: shipa-gen
      SHIPA_GEN_AUTH_MONGO_USER_COLLECTION: users
    ports:
    - "8080:8080"
    restart: on-failure
    depends_on:
      - mongo_db
